q1 = input("Name: ")
q2 = input("Surname: ")
q3 = input("Phone number:  ")
q4 = input("Street name: ")
q5 =  input("House number: ")
q6 = input("Apartment number: ")
q7 = input("City: ")
q8 = input("Index: ")
q9 = input("Country:" )

